# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Ui_Home.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QAbstractSpinBox, QApplication, QDateEdit,
    QFrame, QGridLayout, QHBoxLayout, QLabel,
    QListWidgetItem, QPushButton, QSizePolicy, QVBoxLayout,
    QWidget)

from utils.mywidgets import ListaNotificaciones
from . import resources_rc
from . import resources_rc

class Ui_Home(object):
    def setupUi(self, Home):
        if not Home.objectName():
            Home.setObjectName(u"Home")
        Home.resize(1366, 842)
        self.verticalLayout = QVBoxLayout(Home)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.frame = QFrame(Home)
        self.frame.setObjectName(u"frame")
        self.frame.setMinimumSize(QSize(0, 235))
        self.frame.setStyleSheet(u"QFrame {border: none}")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_3 = QHBoxLayout(self.frame)
        self.horizontalLayout_3.setSpacing(25)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 20)
        self.frame_4 = QFrame(self.frame)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.icon1 = QLabel(self.frame_4)
        self.icon1.setObjectName(u"icon1")
        self.icon1.setMinimumSize(QSize(31, 21))
        self.icon1.setStyleSheet(u"image: url(:/img/resources/images/calendar.png);")

        self.horizontalLayout_2.addWidget(self.icon1)

        self.fechaHoy = QDateEdit(self.frame_4)
        self.fechaHoy.setObjectName(u"fechaHoy")
        self.fechaHoy.setEnabled(False)
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.fechaHoy.setFont(font)
        self.fechaHoy.setStyleSheet(u"QDateEdit {\n"
"	color: rgb(0, 0, 0);\n"
"	background-color: transparent;\n"
"}")
        self.fechaHoy.setFrame(False)
        self.fechaHoy.setReadOnly(True)
        self.fechaHoy.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.fechaHoy.setDisplayFormat(u"'Hoy es' dddd, d 'de' MMMM 'de' yyyy")

        self.horizontalLayout_2.addWidget(self.fechaHoy)


        self.horizontalLayout_3.addWidget(self.frame_4, 0, Qt.AlignLeft|Qt.AlignTop)

        self.logo = QLabel(self.frame)
        self.logo.setObjectName(u"logo")
        self.logo.setMinimumSize(QSize(392, 206))
        self.logo.setMaximumSize(QSize(392, 206))
        self.logo.setPixmap(QPixmap(u":/img/resources/images/logo.png"))
        self.logo.setScaledContents(True)

        self.horizontalLayout_3.addWidget(self.logo, 0, Qt.AlignHCenter|Qt.AlignVCenter)

        self.frame_5 = QFrame(self.frame)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setMinimumSize(QSize(0, 204))
        self.frame_5.setMaximumSize(QSize(16777215, 204))
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.gridLayout = QGridLayout(self.frame_5)
        self.gridLayout.setObjectName(u"gridLayout")
        self.usuario = QLabel(self.frame_5)
        self.usuario.setObjectName(u"usuario")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usuario.sizePolicy().hasHeightForWidth())
        self.usuario.setSizePolicy(sizePolicy)
        font1 = QFont()
        font1.setPointSize(12)
        font1.setItalic(True)
        self.usuario.setFont(font1)
        self.usuario.setText(u"Usuario activo")
        self.usuario.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.usuario, 0, 0, 1, 1, Qt.AlignVCenter)

        self.tipo_usuario = QLabel(self.frame_5)
        self.tipo_usuario.setObjectName(u"tipo_usuario")
        sizePolicy.setHeightForWidth(self.tipo_usuario.sizePolicy().hasHeightForWidth())
        self.tipo_usuario.setSizePolicy(sizePolicy)
        font2 = QFont()
        font2.setPointSize(12)
        self.tipo_usuario.setFont(font2)
        self.tipo_usuario.setStyleSheet(u"color: rgb(114, 114, 114);")
        self.tipo_usuario.setText(u"Tipo de usuario")
        self.tipo_usuario.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.tipo_usuario, 1, 0, 1, 1, Qt.AlignVCenter)

        self.frame_6 = QFrame(self.frame_5)
        self.frame_6.setObjectName(u"frame_6")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy1)
        self.frame_6.setMinimumSize(QSize(400, 120))
        self.frame_6.setMaximumSize(QSize(400, 120))
        self.horizontalLayout_4 = QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.listaNotificaciones = ListaNotificaciones(self.frame_6)
        self.listaNotificaciones.setObjectName(u"listaNotificaciones")
        self.listaNotificaciones.setMinimumSize(QSize(400, 0))
        self.listaNotificaciones.setMaximumSize(QSize(400, 120))
        font3 = QFont()
        font3.setPointSize(10)
        self.listaNotificaciones.setFont(font3)
        self.listaNotificaciones.setStyleSheet(u"QListWidget {\n"
"	alternate-background-color: rgb(240, 240, 240);\n"
"}\n"
"QListWidget::item { margin: 5px; }\n"
"QFrame {border: 2px solid;}")
        self.listaNotificaciones.setFrameShape(QFrame.WinPanel)
        self.listaNotificaciones.setFrameShadow(QFrame.Plain)
        self.listaNotificaciones.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.listaNotificaciones.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.listaNotificaciones.setAlternatingRowColors(True)
        self.listaNotificaciones.setSelectionMode(QAbstractItemView.NoSelection)
        self.listaNotificaciones.setWordWrap(True)

        self.horizontalLayout_4.addWidget(self.listaNotificaciones)


        self.gridLayout.addWidget(self.frame_6, 2, 0, 1, 2)

        self.btFotoPerfil = QPushButton(self.frame_5)
        self.btFotoPerfil.setObjectName(u"btFotoPerfil")
        self.btFotoPerfil.setCursor(QCursor(Qt.PointingHandCursor))
        self.btFotoPerfil.setStyleSheet(u"QPushButton {\n"
"        background-color: transparent;\n"
"        border: none;\n"
"        padding: 0px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgba(255, 255, 255, 0);\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: rgba(255, 255, 255, 0);\n"
"    }")
        icon = QIcon()
        icon.addFile(u":/img/resources/images/user.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btFotoPerfil.setIcon(icon)
        self.btFotoPerfil.setIconSize(QSize(60, 60))
        self.btFotoPerfil.setFlat(True)

        self.gridLayout.addWidget(self.btFotoPerfil, 0, 1, 2, 1)


        self.horizontalLayout_3.addWidget(self.frame_5, 0, Qt.AlignRight|Qt.AlignTop)


        self.verticalLayout.addWidget(self.frame)

        self.frame_2 = QFrame(Home)
        self.frame_2.setObjectName(u"frame_2")
        sizePolicy1.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy1)
        self.frame_2.setStyleSheet(u"QFrame {border: none}")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.gridLayout_2 = QGridLayout(self.frame_2)
        self.gridLayout_2.setSpacing(40)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.frameCrearVenta = QFrame(self.frame_2)
        self.frameCrearVenta.setObjectName(u"frameCrearVenta")
        self.frameCrearVenta.setMinimumSize(QSize(231, 231))
        self.btCrearVenta = QPushButton(self.frameCrearVenta)
        self.btCrearVenta.setObjectName(u"btCrearVenta")
        self.btCrearVenta.setGeometry(QRect(0, 0, 231, 231))
        self.btCrearVenta.setMinimumSize(QSize(231, 231))
        self.label_61 = QLabel(self.frameCrearVenta)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(33, 178, 165, 35))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(False)
        self.label_61.setFont(font4)
        self.label_61.setStyleSheet(u"color: rgb(141, 141, 141);")
        self.label_61.setText(u"Hacer una venta directa o un apartado")
        self.label_61.setAlignment(Qt.AlignCenter)
        self.label_61.setWordWrap(True)
        self.label_62 = QLabel(self.frameCrearVenta)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(60, 28, 111, 111))
        self.label_62.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.label_62.setFrameShadow(QFrame.Plain)
        self.label_62.setText(u"")
        self.label_62.setPixmap(QPixmap(u":/img/resources/images/shopping-cart.png"))
        self.label_62.setScaledContents(True)
        self.label_62.setTextInteractionFlags(Qt.NoTextInteraction)
        self.label_63 = QLabel(self.frameCrearVenta)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(20, 145, 191, 31))
        font5 = QFont()
        font5.setPointSize(14)
        font5.setBold(False)
        self.label_63.setFont(font5)
        self.label_63.setText(u"Realizar una venta")
        self.label_63.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.frameCrearVenta, 0, 0, 1, 1, Qt.AlignHCenter|Qt.AlignVCenter)

        self.frameInventario = QFrame(self.frame_2)
        self.frameInventario.setObjectName(u"frameInventario")
        self.frameInventario.setMinimumSize(QSize(231, 231))
        self.label_73 = QLabel(self.frameInventario)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(60, 28, 111, 111))
        self.label_73.setText(u"")
        self.label_73.setPixmap(QPixmap(u":/img/resources/images/inventory.png"))
        self.label_73.setScaledContents(True)
        self.label_73.setTextInteractionFlags(Qt.NoTextInteraction)
        self.label_74 = QLabel(self.frameInventario)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setGeometry(QRect(20, 145, 191, 31))
        self.label_74.setFont(font5)
        self.label_74.setText(u"Inventario")
        self.label_74.setAlignment(Qt.AlignCenter)
        self.btInventario = QPushButton(self.frameInventario)
        self.btInventario.setObjectName(u"btInventario")
        self.btInventario.setGeometry(QRect(0, 0, 231, 231))
        self.btInventario.setMinimumSize(QSize(231, 231))
        self.label_75 = QLabel(self.frameInventario)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setGeometry(QRect(33, 178, 165, 35))
        self.label_75.setFont(font4)
        self.label_75.setStyleSheet(u"color: rgb(141, 141, 141);")
        self.label_75.setText(u"Administrar materiales del inventario")
        self.label_75.setAlignment(Qt.AlignCenter)
        self.label_75.setWordWrap(True)
        self.btInventario.raise_()
        self.label_73.raise_()
        self.label_74.raise_()
        self.label_75.raise_()

        self.gridLayout_2.addWidget(self.frameInventario, 0, 1, 1, 1, Qt.AlignHCenter|Qt.AlignVCenter)

        self.frameProductos = QFrame(self.frame_2)
        self.frameProductos.setObjectName(u"frameProductos")
        self.frameProductos.setMinimumSize(QSize(231, 231))
        self.label_58 = QLabel(self.frameProductos)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(20, 145, 191, 31))
        self.label_58.setFont(font5)
        self.label_58.setText(u"Productos")
        self.label_58.setAlignment(Qt.AlignCenter)
        self.label_59 = QLabel(self.frameProductos)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(33, 178, 165, 35))
        self.label_59.setFont(font4)
        self.label_59.setStyleSheet(u"color: rgb(141, 141, 141);")
        self.label_59.setText(u"Administrar productos del negocio")
        self.label_59.setAlignment(Qt.AlignCenter)
        self.label_59.setWordWrap(True)
        self.label_60 = QLabel(self.frameProductos)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(60, 28, 111, 111))
        self.label_60.setText(u"")
        self.label_60.setPixmap(QPixmap(u":/img/resources/images/package.png"))
        self.label_60.setScaledContents(True)
        self.label_60.setTextInteractionFlags(Qt.NoTextInteraction)
        self.btProductos = QPushButton(self.frameProductos)
        self.btProductos.setObjectName(u"btProductos")
        self.btProductos.setGeometry(QRect(0, 0, 231, 231))
        self.btProductos.setMinimumSize(QSize(231, 231))
        self.btProductos.raise_()
        self.label_58.raise_()
        self.label_59.raise_()
        self.label_60.raise_()

        self.gridLayout_2.addWidget(self.frameProductos, 0, 2, 1, 1, Qt.AlignHCenter|Qt.AlignVCenter)

        self.frameVentas = QFrame(self.frame_2)
        self.frameVentas.setObjectName(u"frameVentas")
        self.frameVentas.setMinimumSize(QSize(231, 231))
        self.btVentas = QPushButton(self.frameVentas)
        self.btVentas.setObjectName(u"btVentas")
        self.btVentas.setGeometry(QRect(0, 0, 231, 231))
        self.btVentas.setMinimumSize(QSize(231, 231))
        self.label_55 = QLabel(self.frameVentas)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(33, 178, 165, 35))
        self.label_55.setFont(font4)
        self.label_55.setStyleSheet(u"color: rgb(141, 141, 141);")
        self.label_55.setText(u"Ver ventas directas y pedidos realizados")
        self.label_55.setAlignment(Qt.AlignCenter)
        self.label_55.setWordWrap(True)
        self.label_56 = QLabel(self.frameVentas)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(20, 145, 191, 31))
        self.label_56.setFont(font5)
        self.label_56.setText(u"Ventas")
        self.label_56.setAlignment(Qt.AlignCenter)
        self.label_57 = QLabel(self.frameVentas)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(60, 28, 111, 111))
        self.label_57.setText(u"")
        self.label_57.setPixmap(QPixmap(u":/img/resources/images/choices.png"))
        self.label_57.setScaledContents(True)
        self.label_57.setTextInteractionFlags(Qt.NoTextInteraction)

        self.gridLayout_2.addWidget(self.frameVentas, 0, 3, 1, 1, Qt.AlignHCenter|Qt.AlignVCenter)

        self.frameCaja = QFrame(self.frame_2)
        self.frameCaja.setObjectName(u"frameCaja")
        self.frameCaja.setEnabled(True)
        self.frameCaja.setMinimumSize(QSize(231, 231))
        self.btCaja = QPushButton(self.frameCaja)
        self.btCaja.setObjectName(u"btCaja")
        self.btCaja.setGeometry(QRect(0, 0, 231, 231))
        self.btCaja.setMinimumSize(QSize(231, 231))
        self.label_64 = QLabel(self.frameCaja)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(20, 145, 191, 31))
        self.label_64.setFont(font5)
        self.label_64.setText(u"Caja")
        self.label_64.setAlignment(Qt.AlignCenter)
        self.label_65 = QLabel(self.frameCaja)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(33, 178, 165, 35))
        self.label_65.setFont(font4)
        self.label_65.setStyleSheet(u"color: rgb(141, 141, 141);")
        self.label_65.setText(u"Registrar entradas o salidas de dinero de la caja")
        self.label_65.setAlignment(Qt.AlignCenter)
        self.label_65.setWordWrap(True)
        self.label_66 = QLabel(self.frameCaja)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(60, 28, 111, 111))
        self.label_66.setText(u"")
        self.label_66.setPixmap(QPixmap(u":/img/resources/images/cash-register.png"))
        self.label_66.setScaledContents(True)
        self.label_66.setTextInteractionFlags(Qt.NoTextInteraction)

        self.gridLayout_2.addWidget(self.frameCaja, 1, 0, 1, 1, Qt.AlignHCenter|Qt.AlignVCenter)

        self.frameClientes = QFrame(self.frame_2)
        self.frameClientes.setObjectName(u"frameClientes")
        self.frameClientes.setMinimumSize(QSize(231, 231))
        self.label_70 = QLabel(self.frameClientes)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(20, 145, 191, 31))
        self.label_70.setFont(font5)
        self.label_70.setText(u"Clientes")
        self.label_70.setAlignment(Qt.AlignCenter)
        self.label_71 = QLabel(self.frameClientes)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(33, 178, 165, 35))
        self.label_71.setFont(font4)
        self.label_71.setStyleSheet(u"color: rgb(141, 141, 141);")
        self.label_71.setText(u"Administrar clientes del negocio")
        self.label_71.setAlignment(Qt.AlignCenter)
        self.label_71.setWordWrap(True)
        self.btClientes = QPushButton(self.frameClientes)
        self.btClientes.setObjectName(u"btClientes")
        self.btClientes.setGeometry(QRect(0, 0, 231, 231))
        self.btClientes.setMinimumSize(QSize(231, 231))
        self.label_72 = QLabel(self.frameClientes)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(60, 28, 111, 111))
        self.label_72.setText(u"")
        self.label_72.setPixmap(QPixmap(u":/img/resources/images/target.png"))
        self.label_72.setScaledContents(True)
        self.label_72.setTextInteractionFlags(Qt.NoTextInteraction)
        self.btClientes.raise_()
        self.label_70.raise_()
        self.label_71.raise_()
        self.label_72.raise_()

        self.gridLayout_2.addWidget(self.frameClientes, 1, 1, 1, 1, Qt.AlignHCenter|Qt.AlignVCenter)

        self.frameUsuarios = QFrame(self.frame_2)
        self.frameUsuarios.setObjectName(u"frameUsuarios")
        self.frameUsuarios.setMinimumSize(QSize(231, 231))
        self.label_52 = QLabel(self.frameUsuarios)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(20, 145, 191, 31))
        self.label_52.setFont(font5)
        self.label_52.setText(u"Usuarios")
        self.label_52.setAlignment(Qt.AlignCenter)
        self.btUsuarios = QPushButton(self.frameUsuarios)
        self.btUsuarios.setObjectName(u"btUsuarios")
        self.btUsuarios.setGeometry(QRect(0, 0, 231, 231))
        self.btUsuarios.setMinimumSize(QSize(231, 231))
        self.label_53 = QLabel(self.frameUsuarios)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(33, 178, 165, 35))
        self.label_53.setFont(font4)
        self.label_53.setStyleSheet(u"color: rgb(141, 141, 141);")
        self.label_53.setText(u"Administrar usuarios de este sistema")
        self.label_53.setAlignment(Qt.AlignCenter)
        self.label_53.setWordWrap(True)
        self.label_54 = QLabel(self.frameUsuarios)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(60, 28, 111, 111))
        self.label_54.setText(u"")
        self.label_54.setPixmap(QPixmap(u":/img/resources/images/programmer.png"))
        self.label_54.setScaledContents(True)
        self.label_54.setTextInteractionFlags(Qt.NoTextInteraction)
        self.btUsuarios.raise_()
        self.label_52.raise_()
        self.label_53.raise_()
        self.label_54.raise_()

        self.gridLayout_2.addWidget(self.frameUsuarios, 1, 2, 1, 1, Qt.AlignHCenter|Qt.AlignVCenter)

        self.frameReportes = QFrame(self.frame_2)
        self.frameReportes.setObjectName(u"frameReportes")
        self.frameReportes.setMinimumSize(QSize(231, 231))
        self.label_67 = QLabel(self.frameReportes)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(20, 145, 191, 31))
        self.label_67.setFont(font5)
        self.label_67.setText(u"Reportes")
        self.label_67.setAlignment(Qt.AlignCenter)
        self.btReportes = QPushButton(self.frameReportes)
        self.btReportes.setObjectName(u"btReportes")
        self.btReportes.setGeometry(QRect(0, 0, 231, 231))
        self.btReportes.setMinimumSize(QSize(231, 231))
        self.label_68 = QLabel(self.frameReportes)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(33, 178, 165, 35))
        self.label_68.setFont(font4)
        self.label_68.setStyleSheet(u"color: rgb(141, 141, 141);")
        self.label_68.setText(u"Ver reportes de caja y de ventas realizadas")
        self.label_68.setAlignment(Qt.AlignCenter)
        self.label_68.setWordWrap(True)
        self.label_69 = QLabel(self.frameReportes)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(60, 28, 111, 111))
        self.label_69.setText(u"")
        self.label_69.setPixmap(QPixmap(u":/img/resources/images/report.png"))
        self.label_69.setScaledContents(True)
        self.label_69.setTextInteractionFlags(Qt.NoTextInteraction)
        self.btReportes.raise_()
        self.label_67.raise_()
        self.label_68.raise_()
        self.label_69.raise_()

        self.gridLayout_2.addWidget(self.frameReportes, 1, 3, 1, 1, Qt.AlignHCenter|Qt.AlignVCenter)


        self.verticalLayout.addWidget(self.frame_2, 0, Qt.AlignHCenter)

        self.frame_3 = QFrame(Home)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setStyleSheet(u"QFrame {border: none}")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(-1, 20, -1, -1)
        self.btSalir = QPushButton(self.frame_3)
        self.btSalir.setObjectName(u"btSalir")
        self.btSalir.setMinimumSize(QSize(100, 0))
        self.btSalir.setFont(font3)
        self.btSalir.setText(u"Cerrar sesi\u00f3n")

        self.horizontalLayout.addWidget(self.btSalir, 0, Qt.AlignLeft)

        self.btAjustes = QPushButton(self.frame_3)
        self.btAjustes.setObjectName(u"btAjustes")
        self.btAjustes.setMinimumSize(QSize(100, 0))
        self.btAjustes.setFont(font3)
        self.btAjustes.setText(u"Ajustes")
        icon2 = QIcon()
        icon2.addFile(u":/img/resources/images/settings.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btAjustes.setIcon(icon2)
        self.btAjustes.setIconSize(QSize(20, 20))

        self.horizontalLayout.addWidget(self.btAjustes, 0, Qt.AlignRight)


        self.verticalLayout.addWidget(self.frame_3)


        self.retranslateUi(Home)

        self.btCrearVenta.setDefault(True)


        QMetaObject.connectSlotsByName(Home)
    # setupUi

    def retranslateUi(self, Home):
        self.icon1.setText("")
        self.btCrearVenta.setText("")
        self.btInventario.setText("")
        self.btProductos.setText("")
        self.btVentas.setText("")
        self.btCaja.setText("")
        self.btClientes.setText("")
        self.btUsuarios.setText("")
        self.btReportes.setText("")
        pass
    # retranslateUi

